# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 512mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - 1bsearch:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Thi5I5AT3s!
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: onebusername

volumes:
  1bsearch:
